
export const productoIetm = [
    {
      id: 1,
      title: "HP Victus",
      price: 5000,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopVictus.jpg"),
    },
    {
      id: 2,
      title: "Lenovo",
      price: 3500,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopLenovo01.jpg"),
    },
    {
      id: 3,
      title: "ASUS",
      price: 3000,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopAsus01.jpg"),
    },
    {
      id: 4,
      title: "DELL XPS",
      price: 4500,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/DellXPS.jpg"),
    },
    {
      id: 5,
      title: "Hp Omen",
      price: 6500,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopOmen.jpg"),
    },
    {
      id: 6,
      title: "ACER",
      price: 2800,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopAcer01.jpg"),
    },
    {
      id: 7,
      title: "ASUS ZenBook",
      price: 10000,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/AsusZ.jpg"),
    },
    {
      id: 8,
      title: "Hp Envy",
      price: 5500,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/HPEnvy.jpg"),
    },
    {
      id: 9,
      title: "Huawei MateBook",
      price: 4300,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopHuawei.jpg"),
    },
    {
      id: 10,
      title: "GATEWAY",
      price: 4000,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopGatewai.jpg"),
    },
    {
      id: 11,
      title: "Dell G7",
      price: 8500,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/DellG7.jpg"),
    },
    {
      id: 12,
      title: "Acer Nitro",
      price: 6500,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/AcerNitro.jpg"),
    },
    {
      id: 13,
      title: "Surface",
      price: 5500,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/Surface.jpg"),
    },
    {
      id: 14,
      title: "Dell",
      price: 4300,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopDell01.jpg"),
    },
    {
      id: 15,
      title: "Hp Spectre",
      price: 7700,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopHpS.jpg"),
    },
    {
      id: 16,
      title: "Lenovo Legion",
      price: 6800,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopLenovoL.jpg"),
    },
    {
      id: 17,
      title: "Lenovo Yoga",
      price: 5000,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopLenovoY.jpg"),
    },
    {
      id: 18,
      title: "Asus ROG",
      price: 10500,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopAsusRog.jpg"),
    },
    {
      id: 19,
      title: "Gigabyte Aorus",
      price: 15500,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopAorus.jpg"),
    },
    {
      id: 20,
      title: "MSI",
      price: 11800,
      category: "Laptops",
      cantidad: 1,
      image: require("../../images/LaptopMSI.jpg"),
    },
  ];
  